### PR TITLE
enhancement: Added Localization to the app

### PR DESCRIPTION
**Pull request by Axelazo**
Added Localization to the app (English, Spanish)

Users can add translations in .json format in the /src/lib/lang folder and then register them in the I18n Svelte component 

Maybe someone knows how to dinamically load everything in the /lang folder so you don't need to register them manually 

Some strings are still missing to be updated, I'm setting up my environment to have Radarr, Sonarr and Jellyfin

I'm totally new to Svelte, I just followed this guide to add Localization to Reiverr: https://phrase.com/blog/posts/a-step-by-step-guide-to-svelte-localization-with-svelte-i18n-v3/

I really want to help, probably next thing would be to set the language to the users browser lang, and add a setting option to choose the language, or auto-detect it

### CODE REVIEW

**Comment by aleksilassila** [comment]
Looks good, thank you! I haven't done localization on svelte myself either, so I'll read through some documentation and the changes, and merge them asap.

The language options will be visible in the settings page as soon as I have the chance to create one.

**Comment by aleksilassila** [comment]
Hey, any change you could integrate your changes into the new settings page? There's also a couple of new UI components that I'd appreciate if you could translate :)

**Comment by Axelazo** [comment]
Sure! I will start working right away!

**Comment by Axelazo** [comment]
The settings page now allows to change Language of the application (without reload)
Localized a lot of components, some still missing
Better structure for language .json files

I haven't been able to setup Radarr, Sonarr or Jellyfin yet, I'm setting up a homeserver, once I can see the components I will translate them, I find it weird to translate them without seeing them xd

**Comment by Axelazo** [comment]
I was wondering if you could create a Discord server!

**Comment by aleksilassila** [comment]
Looking good! Is this ready to merge now? And yeah that's a good idea, I should do that.

**Comment by Axelazo** [comment]
Yes, should work just fine!

**Review by aleksilassila — COMMENTED** [review]
👌

**Comment by aleksilassila** [comment]
Merged into dev, this pr will be closed when new release is made 👍

**Pull request merged**
