### PR TITLE
update playwright version, add basic tests

### PR DESCRIPTION
**Pull request by AxiomPraxis**
Bumped the playwright version (to match VSCode extension for testability purposes)
Also corrected path for the placeholder image in /library (it was throwing an error).

Added some basic UI tests for each of the 4 main pages:

1. Main (/)
2. Library (/library)
3. Sources (/sources)
4. Settings (/settings)

If these are satisfactory (or not), or if you want any specifics as to what each test or test step does, please let me know.

I can expand on them and make them more modular or if you have any specifics you would like added, please also let me know.

Cheers

### CODE REVIEW

**Comment by AxiomPraxis** [comment]
I believe this also may address #60

**Comment by AxiomPraxis** [comment]
Reviewing this again, may want to drop the package.json and package-lock.json changes and just keep the rest, it may have thrown some arm64/darwin changes into the package-lock, and I don't want to mess with the build process. the tests should still work fine on the older version.

**Comment by jordanf97** [comment]
> it may have thrown some arm64/darwin changes into the package-lock

Looks fine to me, won't break anything 👍

**Comment by aleksilassila** [comment]
Thanks for the contribution! I haven't had time to think about the tests, so these kinds of sanity checks will do nicely. One thing I noticed was that it's probably a good idea to not check if the default values for settings exist as the test will fail if the settings have been changed. Also the first check of finding "Home" element times out for me for some reason. Will merge this anyway, this is a good base for future improvements.

**Pull request merged**
