### PR TITLE
Added view all button into search and enabled query search on library

### PR DESCRIPTION
**Pull request by iGniTJM**
Related to issue: https://github.com/aleksilassila/reiverr/issues/29

Created the View All button on the search and it detects the query parameter in the url when it redirects to the Library section. It automatically filters the items by that query.

Also taken into account i18n

### CODE REVIEW

**Comment by aleksilassila** [comment]
Hey, is this ready to merge? Also, could you clarify your thinking on the functionality? I was thinking since now only 5 search results from tmdb is shown, the view all button would show more of them, but it seems your implementation searches from the library, which only has the items that have been added to radarr sonarr or jellyfin.

**Comment by iGniTJM** [comment]
Hey! Sorry I've just gone into vacations, I've read your comment and realized I didn't exactly think about the same thing, but I'll get around it when I'm back - hold on before any update from me.

Basically I thought the search was for the library itself and not tmdb. Is there any place that lists all the tmdb already? I'm considering whether I should add the scroll or the button then.

Another question would be: should we still keep the functionality done already or not? (Searching the library but changing name of existing button to "Search library") Happy to delete if not

**Comment by aleksilassila** [comment]
Hey, no worries! I’m currently reworking the library page, so keeping the current functionality doesn’t make that much sense imo. We’ll have a working library search in the library page soon. 

When it comes to the functionality and design, I was thinking maybe it could work similar to the requests model where you download items from Sonarr or radarr. See the RequestModal.svelte

Cheers!

**Comment by iGniTJM** [comment]
Hello, I'll have to close this one for now.

I unfortunately don't have as much time as I'd hope to help out for now. I'll try to pickup something once I'm freed up of some things.

I apologize for this

**Pull request closed without merging**
